describe('My First Test', () => {
    it('Visit to Blacked Market Home Page', () => {
      cy.visit('http://localhost:3000')

    //   cy.get('.css-1ynkv7l').should('be.visible').contains('a').click()
    
    // cy.get('.css-1ynkv7l').should('be.visible').contains('cars we love').click()
    cy.scrollTo('bottom')
    cy.scrollTo('top')
    cy.pause()   
    cy.viewport('macbook-15')
    cy.scrollTo('bottom')
    cy.scrollTo('top')
    cy.pause()
    cy.viewport('macbook-13')
    cy.scrollTo('bottom')
    cy.scrollTo('top')
    cy.pause()
    cy.viewport('macbook-11')
    cy.scrollTo('bottom')
    cy.scrollTo('top')
    cy.pause()
    cy.viewport('ipad-2')
    cy.scrollTo('bottom')
    cy.scrollTo('top')
    cy.pause()
    cy.viewport('ipad-mini')
    cy.scrollTo('bottom')
    cy.scrollTo('top')
    cy.pause()
    cy.viewport('iphone-6+')
    cy.scrollTo('bottom')
    cy.scrollTo('top')
    cy.pause()
    cy.viewport('iphone-6')
    cy.scrollTo('bottom')
    cy.scrollTo('top')
    cy.pause()
    cy.viewport('iphone-5')
    cy.scrollTo('bottom')
    cy.scrollTo('top')
    cy.pause()
    cy.viewport('iphone-4')
    cy.scrollTo('bottom')
    cy.scrollTo('top')
    cy.pause()
    cy.viewport('iphone-3')
    cy.scrollTo('bottom')
    cy.scrollTo('top')
    cy.pause()
    cy.viewport('ipad-2', 'portrait')
    cy.scrollTo('bottom')
    cy.scrollTo('top')
    cy.pause()
    cy.viewport('iphone-4', 'landscape')
    cy.scrollTo('bottom')
    cy.scrollTo('top')
    cy.pause()


    })
  })